version: "3.8"
services:
  backend:
    build:
      args:
        - DJANGO_ENV="development"
    env_file:
      - .env.dev
    volumes:
    - ./backend:/app
    ports:
    - 8000:8000
    command: bash -c "chmod +x scripts/wait_for_db.sh
      && scripts/wait_for_db.sh
      && python manage.py makemigrations
      && python manage.py migrate --noinput
      && python manage.py runserver 0.0.0.0:8000"

  db:
    env_file:
      - .env.dev
