version: "3.8"
services:
  frontend:
    build:
      target: production

  backend-api:
    build:
      args:
        - DJANGO_ENV="production"
    env_file:
      - .env.prod
    command: bash -c "chmod +x scripts/wait_for_db.sh
      && scripts/wait_for_db.sh
      && python manage.py makemigrations
      && python manage.py migrate --noinput
      && python manage.py collectstatic --noinput
      && gunicorn src.wsgi:application --bind 0.0.0.0:8000"

  backend-ws:
    env_file:
      - .env.prod
    command: daphne -p 8008 src.asgi:application

  db:
    env_file:
      - .env.prod

  celery-normal-priority:
    env_file:
      - .env.prod
