version: "3.8"
services:
  frontend:
    build:
      context: ./frontend

  backend-api:
    <<: &backend_build
      build:
        context: ./backend
    volumes:
    - django_static:/app/src/static
    - django_media:/app/src/media
    depends_on:
      - db

  backend-ws:
    <<: *backend_build
    build:
      context: backend
    command: celery -A src worker -l info -Q normal_priority -n normal_priority -c 2
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6.0
    restart: always

  celery-normal-priority:
    <<: *backend_build
    build:
      context: backend
    container_name: chatroom_normal_celery
    command: celery -A src worker -l info -Q normal_priority -n normal_priority -c 2
    depends_on:
      - db
      - redis

  nginx:
    build: ./nginx
    ports:
    - 80:80
    depends_on:
      - backend-api
      - frontend
    volumes:
      - django_static:/app/src/static
      - django_media:/app/src/media


volumes:
  django_static:
  django_media:
  db_data:
