# Generated by Django 3.1.4 on 2021-03-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='user_avatar_url',
        ),
        migrations.AddField(
            model_name='connection',
            name='username',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
