# Generated by Django 3.1.4 on 2021-04-12 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20210407_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='chat.room'),
        ),
    ]
