# Generated by Django 3.0.3 on 2020-02-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='username',
            field=models.CharField(default='xd', max_length=255),
            preserve_default=False,
        ),
    ]
