# Generated by Django 3.0.3 on 2020-02-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200220_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='is_user_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connection',
            name='user_avatar_url',
            field=models.CharField(default='avatars/default.png', max_length=255),
        ),
    ]
